spring:
  datasource:
    password: Rm@98#03$16
    url: jdbc:mysql://localhost:3306/serverm
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true